/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.docente.view;

import com.docente.controller.ControllerSection;
import com.docente.implementation.ImplementationSection;
import com.docente.model.Section;
import com.docente.view.component.ComponentJTableSection;
import com.docente.view.component.ComponentJTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DonTulio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private ImplementationSection impltSection;
    public Main() {
        initComponents();
        impltSection = ControllerSection.newInstance();
        this.setInitialConfig();
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        txtCode = new ComponentJTextField("Write Section");
        txtSection = new ComponentJTextField("Write Code");
        jLabelSeparator = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSection = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Main"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jPanelBase.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBase.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBase.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanelBase.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelBase.setPreferredSize(new java.awt.Dimension(800, 600));

        txtCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSection.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelSeparator.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelSeparator.setText("-");
        jLabelSeparator.setAlignmentY(0.0F);
        jLabelSeparator.setPreferredSize(new java.awt.Dimension(8, 20));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Search or Create");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableSection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableSection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSection.setAutoscrolls(false);
        jTableSection.setGridColor(new java.awt.Color(255, 255, 255));
        jTableSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSectionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSection);

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            StringBuilder sectionName = new StringBuilder();
            sectionName.append(txtCode.getText().trim());
            sectionName.append("-");
            sectionName.append(txtSection.getText().trim());
            Section section = new Section(sectionName.toString());
            fillTable(section);
//            int id =  impltSection.add(section);
//            if(id>1){
//                System.out.println("Agregado : " + id);
//            }
        } catch (Exception e) {
            fillTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSectionMouseClicked
        if(evt.getClickCount() == 2){
            ComponentJTableSection model = ((ComponentJTableSection)jTableSection.getModel());
            Section selected = model.getSectionFromPosition(jTableSection.getSelectedRow());
            new Mark(selected).setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_jTableSectionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main();
            }
        });
    }

    private void setInitialConfig() {
        fillTable();
        this.setSize(800, 600); 
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void fillTable(Section findSection) throws Exception{
        ComponentJTableSection model = new ComponentJTableSection(
                impltSection.findElements(findSection)
        );
        if(model.getCount()==0){
            JOptionPane.showMessageDialog(null, 
                        "This section does not exist, it will be created.",
                        "Section not found",
                        JOptionPane.OK_OPTION);
            int id = impltSection.add(findSection);
            Section newSecction = new Section(id, findSection.getSectionName(), (byte)0);
            new Mark(newSecction).setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, 
                    String.format("There are a %s backups", model.getCount())
            );
        }
        jTableSection.setModel(model);
    }
    private void fillTable(){
        ComponentJTableSection model = new ComponentJTableSection(
                impltSection.getElements()
        );
        JOptionPane.showMessageDialog(null, 
                String.format("There are a %s backups", model.getCount())
        );
        jTableSection.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelSeparator;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSection;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtSection;
    // End of variables declaration//GEN-END:variables
}
